baseURL = 'http://hugoonghai.github.io'
languageCode = 'en-us'
title = 'Hugo Onghai'
theme = 'hyde'

[params]
	themeColor = "theme-base-0d"
	sidebarImage = "/images/ProfilePicture.jpg"
	description = "My Personal Site." 	

[Menus]
	main = [
		{Name = "Github", URL = "https://github.com/HugoOnghai"},
		{Name = "SoundCloud", URL = "https://soundcloud.com/hugo-onghai"},
		{Name = "LinkedIn", URL = "https://www.linkedin.com/in/hugo-onghai/"},
	]
